# GenAI creates Kubernetes service definitions to expose your application.

apiVersion: v1
kind: Service
metadata:
  name: genai-java-app-service
spec:
  selector:
    app: genai-java-app
  ports:
    - protocol: TCP
      port: 80 # The port on which this service will be exposed within the cluster.
      targetPort: 8080 # The port on the pods that the service will forward traffic to (GenAI infers from app).
  type: LoadBalancer # GenAI chooses appropriate service type (ClusterIP, NodePort, LoadBalancer) based on deployment needs.